### PR TITLE
Fix memory leak using custom BUILTIN_MODIFIERS object, fix #28

### LINKED ISSUE #28: Container memory leak
Hi,

based on the @ryanto's video https://embermap.com/topics/memory-leaks/do-i-have-a-memory-leak (thanks), I've found that this add-on is leaking container in tests in our application.

I've created this branch https://github.com/bobisjan/ember-memory-leaks/tree/ember-angle-bracket-invocation-polyfill, which reproduces the issue.

**new app without add-on**

screen shot 2018-07-17 at 13 33 56

**new app with add-on**

screen shot 2018-07-17 at 13 37 58

I'll try to deep dive into this, but I'm not familiar with these internals 🙈.

Thanks for this add-on 🤩.

### PR DESCRIPTION
**Pull request by bobisjan**

### CODE REVIEW

**Comment by bobisjan** [comment]
I'm not sure if this is a correct fix of memory leak in #28, but it removes it in our application.

File: vendor/angle-bracket-invocation-polyfill/runtime-polyfill.js [hunk 1]
```diff
@@ -95,6 +95,10 @@ import { lte, gte } from 'ember-compatibility-helpers';
             }
           }
 
+          runtimeResolver.builtInModifiers = {
```
Comment (rwjblue) [inline vendor/angle-bracket-invocation-polyfill/runtime-polyfill.js]: Can you tweak this slightly to:

```js 
runtimeResolver.builtInModifiers = Ember.assign({}, runtimeResolver.builtInModifiers);
```

I believe it should have the same benefit (not mutating the global state), but also preserve any other items in the built in modifiers.

Comment (bobisjan) [reply vendor/angle-bracket-invocation-polyfill/runtime-polyfill.js]: Yes, will do.

BTW I've found another leak with `CURLY_COMPONENT_MANAGER` few lines below (https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill/blob/master/vendor/angle-bracket-invocation-polyfill/runtime-polyfill.js#L166-L169), I can update this PR (or create a new one) with something like

```javascript
let customManager = Ember.assign({}, manager);
```

Comment (bobisjan) [reply vendor/angle-bracket-invocation-polyfill/runtime-polyfill.js]: I've updated the PR, but left `CURLY_COMPONENT_MANAGER` issue to a separate investigation.

Comment (rwjblue) [reply vendor/angle-bracket-invocation-polyfill/runtime-polyfill.js]: Ya, updating CURLY_COMPONENT_MANAGER does make sense to me but I'm happy to just review that in a separate PR.

**Comment by rwjblue** [comment]
restarted CI (failures seem unrelated)

File: vendor/angle-bracket-invocation-polyfill/runtime-polyfill.js (hunk 1 above)
Comment (bobisjan) [reply vendor/angle-bracket-invocation-polyfill/runtime-polyfill.js]: Yeah, I'll try to provide a separate PR, right now I'm still facing with `CURLY_COMPONENT_MANAGER` leak, because using `Ember.assign` breaks setting attributes on components from parent template.

**Comment by ryanto** [comment]
wow nice job @bobisjan 🎉
