### PR TITLE
Fix transform to not touch native <input>

### LINKED ISSUE #78: Regressions of v2.0.0
I am seeing some failing tests in another addon apparently caused by the recent release: https://travis-ci.org/kaliber5/ember-bootstrap/builds/566989699. 🤔

Will investigate and try to fix asap!

### PR DESCRIPTION
**Pull request by simonihmig**
Fixes #78

That was a pretty stupid one: the transform would treat `<input />` the same as `<Input />`, i.e. transform it to `{{input}}`. 🤦‍♂️
Fixed that, added a test, and also tested it with the test suite of ember-bootstrap, which uncovered this issue as reported in #78.

Had to extract some of the existing helpers that work around the issue of earlier Ember version's AST returning the lower-cased tag name, to reuse them here.

### CODE REVIEW

File: lib/ast-input-transform.js [hunk 1]
```diff
@@ -104,15 +108,15 @@ class AngleBracketInputPolyfill {
 
     let visitor = {
       ElementNode(node) {
-        let tag = node.tag.toLowerCase();
```
Comment (simonihmig) [inline lib/ast-input-transform.js]: That's the culprit, which I copy pasted blindly from the link-to transform, which does not work here obviously 🙈
Sorry about that!

**Comment by rwjblue** [comment]
Thanks for digging into this!
